src/Entity/Configuracion.php
<?php

namespace App\Entity;

use App\Repository\ConfiguracionRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ConfiguracionRepository::class)
 */
class Configuracion
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $rotacion_evolutivo;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getRotacionEvolutivo(): ?int
    {
        return $this->rotacion_evolutivo;
    }

    public function setRotacionEvolutivo(int $rotacion_evolutivo): self
    {
        $this->rotacion_evolutivo = $rotacion_evolutivo;

        return $this;
    }
}

src/Form/ConfiguracionType.php
<?php

namespace App\Form;

use App\Entity\Configuracion;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ConfiguracionType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('rotacion_evolutivo')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Configuracion::class,
        ]);
    }
}

src/Controller/ConfiguracionController.php
<?php

namespace App\Controller;

use App\Entity\Configuracion;
use App\Form\ConfiguracionType;
use App\Repository\ConfiguracionRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/configuracion")
 */
class ConfiguracionController extends AbstractController
{
    /**
     * @Route("/", name="configuracion_index", methods={"GET"})
     */
    public function index(ConfiguracionRepository $configuracionRepository): Response
    {
        return $this->render('configuracion/index.html.twig', [
            'configuracions' => $configuracionRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="configuracion_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $configuracion = new Configuracion();
        $form = $this->createForm(ConfiguracionType::class, $configuracion);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($configuracion);
            $entityManager->flush();

            return $this->redirectToRoute('configuracion_index');
        }

        return $this->render('configuracion/new.html.twig', [
            'configuracion' => $configuracion,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="configuracion_show", methods={"GET"})
     */
    public function show(Configuracion $configuracion): Response
    {
        return $this->render('configuracion/show.html.twig', [
            'configuracion' => $configuracion,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="configuracion_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Configuracion $configuracion): Response
    {
        $form = $this->createForm(ConfiguracionType::class, $configuracion);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('configuracion_index');
        }

        return $this->render('configuracion/edit.html.twig', [
            'configuracion' => $configuracion,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="configuracion_delete", methods={"POST"})
     */
    public function delete(Request $request, Configuracion $configuracion): Response
    {
        if ($this->isCsrfTokenValid('delete'.$configuracion->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($configuracion);
            $entityManager->flush();
        }

        return $this->redirectToRoute('configuracion_index');
    }
}

templates/configuracion/_delete_form.html.twig
<form method="post" action="{{ path('configuracion_delete', {'id': configuracion.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ configuracion.id) }}">
    <button class="btn">Delete</button>
</form>

templates/configuracion/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Configuracion{% endblock %}

{% block body %}
    <h1>Edit Configuracion</h1>

    {{ include('configuracion/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('configuracion_index') }}">back to list</a>

    {{ include('configuracion/_delete_form.html.twig') }}
{% endblock %}

templates/configuracion/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Configuracion index{% endblock %}

{% block body %}
    <h1>Configuracion index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Rotacion_evolutivo</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for configuracion in configuracions %}
            <tr>
                <td>{{ configuracion.id }}</td>
                <td>{{ configuracion.rotacionEvolutivo }}</td>
                <td>
                    <a href="{{ path('configuracion_show', {'id': configuracion.id}) }}">show</a>
                    <a href="{{ path('configuracion_edit', {'id': configuracion.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="3">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('configuracion_new') }}">Create new</a>
{% endblock %}

templates/configuracion/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Configuracion{% endblock %}

{% block body %}
    <h1>Create new Configuracion</h1>

    {{ include('configuracion/_form.html.twig') }}

    <a href="{{ path('configuracion_index') }}">back to list</a>
{% endblock %}

templates/configuracion/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Configuracion{% endblock %}

{% block body %}
    <h1>Configuracion</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ configuracion.id }}</td>
            </tr>
            <tr>
                <th>Rotacion_evolutivo</th>
                <td>{{ configuracion.rotacionEvolutivo }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('configuracion_index') }}">back to list</a>

    <a href="{{ path('configuracion_edit', {'id': configuracion.id}) }}">edit</a>

    {{ include('configuracion/_delete_form.html.twig') }}
{% endblock %}