src/Entity/Ingreso.php
<?php

namespace App\Entity;

use App\Repository\IngresoRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=IngresoRepository::class)
 */
class Ingreso
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $fecha_entrada;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $fecha_alta;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $estado;

    /**
     * @ORM\Column(type="datetime")
     */
    private $fecha_confirmacion;

    /**
     * @ORM\ManyToOne(targetEntity=Usuario::class, inversedBy="ingresos")
     */
    private $usuario;

    /**
     * @ORM\ManyToOne(targetEntity=Centro::class, inversedBy="ingresos")
     * @ORM\JoinColumn(nullable=true)
     */
    private $centro;

    /**
     * @ORM\OneToMany(targetEntity=Prueba::class, mappedBy="ingreso", orphanRemoval=true,cascade={"persist"})
     */
    private $pruebas;

    /**
     * @ORM\ManyToOne(targetEntity=Paciente::class, inversedBy="ingresos",cascade={"persist"})
     */
    private $paciente;



    /**
     * @ORM\ManyToOne(targetEntity=Sala::class, inversedBy="ingresos")
     */
    private $sala;

    /**
     * @ORM\ManyToOne(targetEntity=Cama::class)
     */
    private $cama;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $fecha_transportado;

    public function __construct()
    {
        $this->pruebas = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFechaEntrada(): ?\DateTimeInterface
    {
        return $this->fecha_entrada;
    }

    public function setFechaEntrada(?\DateTimeInterface $fecha_entrada): self
    {
        $this->fecha_entrada = $fecha_entrada;

        return $this;
    }

    public function getFechaAlta(): ?\DateTimeInterface
    {
        return $this->fecha_alta;
    }

    public function setFechaAlta(?\DateTimeInterface $fecha_alta): self
    {
        $this->fecha_alta = $fecha_alta;

        return $this;
    }

    public function getEstado(): ?string
    {
        return $this->estado;
    }

    public function setEstado(string $estado): self
    {
        $this->estado = $estado;

        return $this;
    }

    public function getFechaConfirmacion(): ?\DateTimeInterface
    {
        return $this->fecha_confirmacion;
    }

    public function setFechaConfirmacion(\DateTimeInterface $fecha_confirmacion): self
    {
        $this->fecha_confirmacion = $fecha_confirmacion;

        return $this;
    }

    public function getUsuario(): ?Usuario
    {
        return $this->usuario;
    }

    public function setUsuario(?Usuario $usuario): self
    {
        $this->usuario = $usuario;

        return $this;
    }

    public function getCentro(): ?Centro
    {
        return $this->centro;
    }

    public function setCentro(?Centro $centro): self
    {
        $this->centro = $centro;

        return $this;
    }

    /**
     * @return Collection|Prueba[]
     */
    public function getPruebas(): Collection
    {
        return $this->pruebas;
    }

    public function addPrueba(Prueba $prueba): self
    {
        if (!$this->pruebas->contains($prueba)) {
            $this->pruebas[] = $prueba;
            $prueba->setIngreso($this);
        }

        return $this;
    }

    public function removePrueba(Prueba $prueba): self
    {
        if ($this->pruebas->removeElement($prueba)) {
            // set the owning side to null (unless already changed)
            if ($prueba->getIngreso() === $this) {
                $prueba->setIngreso(null);
            }
        }

        return $this;
    }

    public function getPaciente(): ?Paciente
    {
        return $this->paciente;
    }

    public function setPaciente(?Paciente $paciente): self
    {
        $this->paciente = $paciente;

        return $this;
    }



    public function getSala(): ?Sala
    {
        return $this->sala;
    }

    public function setSala(?Sala $sala): self
    {
        $this->sala = $sala;

        return $this;
    }

    public function getCama(): ?Cama
    {
        return $this->cama;
    }

    public function setCama(?Cama $cama): self
    {
        $this->cama = $cama;

        return $this;
    }

    public function getFechaTransportado(): ?\DateTimeInterface
    {
        return $this->fecha_transportado;
    }

    public function setFechaTransportado(?\DateTimeInterface $fecha_transportado): self
    {
        $this->fecha_transportado = $fecha_transportado;

        return $this;
    }

}

src/Form/IngresoType.php
<?php

namespace App\Form;

use App\Entity\Ingreso;
use App\EventListener\AddFieldSubscriber;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class IngresoType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder


            ->add('centro', null, ['attr'=>['class'=>'selectpicker form-control'],'placeholder'=>'Provincia',
                'required' => true,
                'multiple' => false,
                'expanded' => false

            ])

        ;

        $builder->addEventSubscriber(new AddFieldSubscriber());

            }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Ingreso::class,    'validation_groups' => false,
        ]);
    }
}

src/Controller/IngresoController.php
<?php

namespace App\Controller;

use App\Entity\Cama;
use App\Entity\Centro;
use App\Entity\EstadoCama;
use App\Entity\Ingreso;
use App\Entity\Notificacion;
use App\Entity\Sala;
use App\Form\IngresoType;
use App\Repository\IngresoRepository;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/ingreso")
 */
class IngresoController extends AbstractController
{
    /**
     * @Route("/", name="ingreso_index", methods={"GET"})
     */
    public function index(IngresoRepository $ingresoRepository): Response
    {
        return $this->render('ingreso/index.html.twig', [
            'ingresos' => $ingresoRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="ingreso_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $ingreso = new Ingreso();
        $form = $this->createForm(IngresoType::class, $ingreso);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($ingreso);
            $entityManager->flush();

            return $this->redirectToRoute('ingreso_index');
        }

        return $this->render('ingreso/new.html.twig', [
            'ingreso' => $ingreso,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="ingreso_show", methods={"GET"})
     */
    public function show(Ingreso $ingreso): Response
    {
        return $this->render('ingreso/show.html.twig', [
            'ingreso' => $ingreso,
        ]);
    }

   /**
     * @Route("/{id}/edit", name="ingreso_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Ingreso $ingreso): Response
    {
        $form = $this->createForm(IngresoType::class, $ingreso);

        $entityManager=$this->getDoctrine()->getManager();
        $centros=[];
        if($this->getUser()->getRoles()=="ROLE_COORDINADOR_MUNICIPAL"){
            $centros= $entityManager->getRepository(Centro::class)->findCentrosRol($this->getUser()->getProvincia()->getId(),$this->getUser()->getMunicipio()->getId());
        }else   if($this->getUser()->getRoles()=="ROLE_COORDINADOR_PROVINCIAL") {
            $centros= $entityManager->getRepository(Centro::class)->findCentrosRol($this->getUser()->getProvincia()->getId(),null);
        }
        $form->remove("centro")
        ->add('centro', EntityType::class, ['class'=>Centro::class,'choice_label' => 'nombre','attr'=>['class'=>'selectpicker form-control centro'],'placeholder'=>'Centro',
        'required' => true,
        'multiple' => false,
        'expanded' => false,
        'choices'=>$centros
    ]);
        if($ingreso->getSala()==null){

            $form->add('sala', null, ['attr'=>['class'=>'selectpicker form-control sala'],'placeholder'=>'Sala',
                'required' => true,
                'multiple' => false,
                'expanded' => false,
                'choices'=>[]

            ]) ->add('cama', null, ['attr'=>['class'=>'selectpicker form-control cama'],'placeholder'=>'Cama',
                'required' => true,
                'multiple' => false,
                'expanded' => false,
                'choices'=>[]

            ]);
        }else{
          $camas=$ingreso->getSala()->CamasSinOcupar();
          $camas[]=$ingreso->getCama();
            $form->add('sala', EntityType::class, ['class'=>Sala::class,'choice_label' => 'nombre','attr'=>['class'=>'selectpicker form-control sala'],'placeholder'=>'Sala',
                'required' => true,
                'multiple' => false,
                'expanded' => false,
                'choices'=>$ingreso->getCentro()->getSalas()

            ]) ->add('cama', EntityType::class, ['class'=>Cama::class,'choice_label' => 'numero','attr'=>['class'=>'selectpicker form-control cama'],'placeholder'=>'Cama',
                'required' => true,
                'multiple' => false,
                'expanded' => false,
                'choices'=>$camas
            ]);
        }
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $peticion=$request->request->get("ingreso");
            $sala=  $this->getDoctrine()->getManager()->getRepository(Sala::class)->find($peticion['sala']);
            $centro=  $this->getDoctrine()->getManager()->getRepository(Centro::class)->find($peticion['centro']);
            $cama=  $this->getDoctrine()->getManager()->getRepository(Cama::class)->find($peticion['cama']);
            $cama->setEstado($this->getDoctrine()->getManager()->getRepository(EstadoCama::class)->Obtener("Ocupada"));
            $ingreso->setSala($sala);
            $ingreso->setCentro($centro);
            $ingreso->setCama($cama);
            $ingreso->setEstado("Pendiente");
            $this->getDoctrine()->getManager()->flush();
//NOTIFICAR AL QUE LO INGRESO PARA SU RECOGIDA

            if($this->getUser()->getRoles()=="ROLE_COORDINADOR_MUNICIPAL") {
                $notificacion = new Notificacion();
                $notificacion->setPaciente($ingreso->getPaciente());
                $notificacion->setDestino($ingreso->getUsuario()->getId());
                $notificacion->setOrigen($this->getUser());
                $notificacion->setFechaEnvio(new \DateTime("now"));
                $notificacion->setMensaje("Se le asigno ubicacion en " . $centro->getNombre() . " al paciente");
                $entityManager->persist($notificacion);
                $entityManager->flush();
            }else if($this->getUser()->getRoles()=="ROLE_COORDINADOR_PROVINCIAL"){
                $notificacion = new Notificacion();
                $notificacion->setPaciente($ingreso->getPaciente());
                $notificacion->setDestino("ROLE_COORDINADOR_MUNICIPAL");
                $notificacion->setOrigen($this->getUser());
                $notificacion->setFechaEnvio(new \DateTime("now"));
                $notificacion->setMensaje("Se le asigno ubicacion en el hospital " . $centro->getNombre() . " al paciente");
                $entityManager->persist($notificacion);
                $entityManager->flush();
            }

//NOTIFICAR AL CENTRO DE SU POSIBLE ARRIBO
            foreach ($centro->getUsuarios() as $u) {
                $notice = new Notificacion();
                $notice->setPaciente($ingreso->getPaciente());
                $notice->setDestino($u->getId());
                $notice->setOrigen($this->getUser());
                $notice->setFechaEnvio(new \DateTime("now"));
                $notice->setMensaje("Se le asigno  a su centro el  paciente");
                $entityManager->persist($notice);
                $entityManager->flush();
            }
            return $this->redirectToRoute('paciente_index');
        }

        return $this->render('ingreso/edit.html.twig', [
            'ingreso' => $ingreso,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="ingreso_delete", methods={"POST"})
     */
    public function delete(Request $request, Ingreso $ingreso): Response
    {
        if ($this->isCsrfTokenValid('delete'.$ingreso->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($ingreso);
            $entityManager->flush();
        }

        return $this->redirectToRoute('ingreso_index');
    }
}

templates/ingreso/_delete_form.html.twig
<form method="post" action="{{ path('ingreso_delete', {'id': ingreso.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ ingreso.id) }}">
    <button class="btn">Delete</button>
</form>

templates/ingreso/_form.html.twig
{{ form_start(form) }}


<div>
    {{ form_errors(form.centro,{'attr':{'class':'alert alert-error'} } ) }}
    {{ form_widget(form.centro) }}

</div>

{{ form_widget(form) }}
<br>
<div class="row">
    <div class="col-md-6">
        <button type="button" onclick="window.location='{{  path('paciente_index') }}';" class="btn btn-danger">Cancelar</button>
    </div>
    <div class="col-md-6">
        <button class="btn btn-success">{{ button_label|default('Guardar') }}</button>
    </div>
</div>

<div class="clearfix"></div>

{{ form_end(form) }}

templates/ingreso/edit.html.twig
{% extends 'base.html.twig' %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            <div class=" form ">
                <section class="login_content">
                    <h1>Asignar Ubicacion</h1>
                    <div class="row">
                        <div class="col-md-8">
                            <div class="x_panel">
                                <div class="x_title">
                                    <h2>Paciente</h2>
                                    <ul class="nav navbar-right panel_toolbox">
                                        <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                                        </li>
                                    </ul>
                                    <div class="clearfix"></div>
                                </div>
                                <div class="x_content">

                                    <div class="row">
                                        <div class="col-md-12">
                                            <div class="row">
                                                <div class="col-md-12" style="text-align: center">
                                                   <h2>Datos Generales</h2>
                                                </div>

                                            </div>
                                            <div class="row">
                                                <div class="col-md-3"><b>Nombre</b><br> {{ ingreso.paciente.nombre }}</div>

                                                <div class="col-md-3"><b>Apellidos</b><br>{{ ingreso.paciente.apellidos }}</div>

                                                <div class="col-md-3"><b>CI/Pasaporte</b><br>{% if ingreso.paciente.pasaporte==null %}

                                                        {% if(ingreso.paciente.carnet!=null) %}

                                                            {{ ingreso.paciente.carnet }}
                                                        {% endif %}
                                                    {% else %}
                                                        {{ ingreso.paciente.pasaporte }}
                                                    {% endif %}
                                                </div>
                                                <div class="col-md-3"><b>Edad</b><br> {{ ingreso.paciente.edad }}</div>

                                            </div>
<br>
                                            <div class="row">

                                                <div class="col-md-3"><b>Sexo</b><br>{{ ingreso.paciente.getNonimalSex }}</div>
                                                <div class="col-md-3"><b>Direccion CI</b><br>{{ ingreso.paciente.direccionci }}</div>
                                                <div class="col-md-3"><b>Direccion Residencia</b><br>{{ ingreso.paciente.direccionres }}</div>
                                                <div class="col-md-3"><b>Color de la piel</b><br>{{ ingreso.paciente.getNominalColor }}</div>


                                            </div>
                                            <br>
                                            <div class="row">

                                                <div class="col-md-3"><b>Provincia</b><br>{{ ingreso.paciente.provincia }}</div>
                                                <div class="col-md-3"><b>Municipio</b><br>{{ ingreso.paciente.municipio }}</div>
                                                <div class="col-md-3"><b>Area de Salud</b><br>{{ ingreso.paciente.area }}</div>
                                                <div class="col-md-3"><b>Consultorio</b><br>{{ ingreso.paciente.consultorio }}</div>


                                            </div>
                                            <br>

                                            <div class="row">
                                                <div class="col-md-12" style="text-align: center">
                                                    <h2>Clasificaciones</h2>
                                                </div>

                                            </div>
                                            <div class="row">
                                                <div class="col-md-3"><b>Epidemiologia</b><br> {{ ingreso.paciente.epidemiologia }}</div>

                                                <div class="col-md-3"><b>Sintomatologia</b><br>{{ ingreso.paciente.sintomatologia }}</div>

                                                <div class="col-md-3"><b>Riesgo</b><br> {{ ingreso.paciente.riesgo }} </div>
                                                <div class="col-md-3"><b>Transportable</b><br> {{ ingreso.paciente.transportable }}</div>

                                            </div>
<br>
                                            <div class="row">
                                                <div class="col-md-3"><b>Vacuna</b><br> {{ ingreso.paciente.vacuna }}</div>

                                                <div class="col-md-3"><b>Cant.Dosis</b><br>{{ ingreso.paciente.dosis }}</div>

                                                <div class="col-md-4"><b>Requiere transporte sanitario</b><br>{% if ingreso.paciente.transportesanitario %}SI{% else %}NO{% endif %}  </div>

                                            </div>
                                            <br>


                                            <div class="row">
                                                <div class="col-md-12" style="text-align: center">
                                                    <h2>Antecedentes Personales</h2>
                                                </div>

                                            </div>
                                            <div class="row">
                                                <div class="col-md-1"><b>HTA</b><br> {% if  ingreso.paciente.hta %}SI{% else %}NO{% endif %} </div>
                                                <div class="col-md-1"><b>DM</b><br> {% if  ingreso.paciente.dm %}SI{% else %}NO{% endif %} </div>
                                                <div class="col-md-1"><b>EPOC</b><br> {% if  ingreso.paciente.epoc %}SI{% else %}NO{% endif %} </div>
                                                <div class="col-md-1"><b>AB</b><br> {% if  ingreso.paciente.ab %}SI{% else %}NO{% endif %} </div>

                                                <div class="col-md-1"><b>CI</b><br> {% if  ingreso.paciente.ci %}SI{% else %}NO{% endif %} </div>
                                                <div class="col-md-1"><b>VIH</b><br> {% if  ingreso.paciente.vih %}SI{% else %}NO{% endif %} </div>
                                                <div class="col-md-1"><b>Cancer</b><br> {% if  ingreso.paciente.cancer %}SI{% else %}NO{% endif %} </div>
                                                <div class="col-md-1"><b>Obesidad</b><br> {% if  ingreso.paciente.obeso %}SI{% else %}NO{% endif %} </div>
                                                <div class="col-md-4"><b>Trastornos Siquiatricos</b><br> {% if  ingreso.paciente.trastornos %}SI{% else %}NO{% endif %} </div>

                                            </div>
                                            <br>
                                            <div class="row">
                                                <div class="col-md-4"><b>Inmunodeprimido</b><br> {% if  ingreso.paciente.inmunodeprimido %}SI{% else %}NO{% endif %} </div>

                                                <div class="col-md-4"><b>Otros APP</b><br> {% if  ingreso.paciente.otros %}SI{% else %}NO{% endif %} </div>
                                            </div>
                                            <br>
                                            <div class="row">
                                                <div class="col-md-12" style="text-align: center">
                                                    <h2>Signos Vitales</h2>
                                                </div>

                                            </div>
                                            <div class="row">
                                                <div class="col-md-3"><b>Frecuencia Respiratoria</b><br> {{ ingreso.paciente.fr }}</div>
                                                <div class="col-md-3"><b>Frecuencia Cardiaca</b><br> {{ ingreso.paciente.fc }}</div>
                                                <div class="col-md-3"><b>Tension Arterial</b><br> {{ ingreso.paciente.ta }}</div>
                                                <div class="col-md-3"><b>Saturacion de Oxigeno</b><br> {{ ingreso.paciente.saturacion }}</div>

                                            </div>
                                            <br>
                                            <div class="row">
                                                <div class="col-md-12" style="text-align: center">
                                                    <h2>Datos Adicionales</h2>
                                                </div>

                                            </div>
                                            <div class="row">
                                                <div class="col-md-12"><br> {{ ingreso.paciente.observaciones }}</div>

                                            </div>
                                            <br>
                                        </div>


                                    </div>
                                </div>

                            </div>

                        </div>
                        <div style="position: fixed;right: 0;" class="col-md-3">
                            <div class="x_panel">
                                <div class="x_title">
                                    <h2>Ubicar Paciente</h2>
                                    <ul class="nav navbar-right panel_toolbox">
                                        <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                                        </li>
                                    </ul>
                                    <div class="clearfix"></div>
                                </div>
                                <div class="x_content">

                                    <div class="row">

                                        <div class="col-md-12">   {{ include('ingreso/_form.html.twig') }}</div>


                                    </div>
                                </div>

                            </div>

                        </div>
                    </div>


                </section>
            </div>
        </div>
    </div>
{% endblock %}

templates/ingreso/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ingreso index{% endblock %}

{% block body %}
    <h1>Ingreso index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Fecha_entrada</th>
                <th>Fecha_salida</th>
                <th>Estado</th>
                <th>Fecha_confirmacion</th>
                <th>Transportado</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for ingreso in ingresos %}
            <tr>
                <td>{{ ingreso.id }}</td>
                <td>{{ ingreso.fechaEntrada ? ingreso.fechaEntrada|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ ingreso.fechaSalida ? ingreso.fechaSalida|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ ingreso.estado }}</td>
                <td>{{ ingreso.fechaConfirmacion ? ingreso.fechaConfirmacion|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ ingreso.transportado ? 'Yes' : 'No' }}</td>
                <td>
                    <a href="{{ path('ingreso_show', {'id': ingreso.id}) }}">show</a>
                    <a href="{{ path('ingreso_edit', {'id': ingreso.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('ingreso_new') }}">Create new</a>
{% endblock %}

templates/ingreso/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Ingreso{% endblock %}

{% block body %}
    <h1>Create new Ingreso</h1>

    {{ include('ingreso/_form.html.twig') }}

    <a href="{{ path('ingreso_index') }}">back to list</a>
{% endblock %}

templates/ingreso/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ingreso{% endblock %}

{% block body %}
    <h1>Ingreso</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ ingreso.id }}</td>
            </tr>
            <tr>
                <th>Fecha_entrada</th>
                <td>{{ ingreso.fechaEntrada ? ingreso.fechaEntrada|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Fecha_salida</th>
                <td>{{ ingreso.fechaSalida ? ingreso.fechaSalida|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Estado</th>
                <td>{{ ingreso.estado }}</td>
            </tr>
            <tr>
                <th>Fecha_confirmacion</th>
                <td>{{ ingreso.fechaConfirmacion ? ingreso.fechaConfirmacion|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Transportado</th>
                <td>{{ ingreso.transportado ? 'Yes' : 'No' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('ingreso_index') }}">back to list</a>

    <a href="{{ path('ingreso_edit', {'id': ingreso.id}) }}">edit</a>

    {{ include('ingreso/_delete_form.html.twig') }}
{% endblock %}